title: Weathermaker Consulting
email: weathermaker@dustinarmstrong.info
description: A new level of consulting strategy.
baseurl:
url: 
twitter_username: weathermakerco
github_username: weathermaker
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-admin
exclude:
  - Gemfile
  - Gemfile.lock
